---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  labels:
    app: ${CIRCLE_PROJECT_REPONAME}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
  template:
    metadata:
      labels:
        app: ${CIRCLE_PROJECT_REPONAME}
    spec:
      containers:
        - name: ${CIRCLE_PROJECT_REPONAME}
          image: gcr.io/${K8S_GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
      restartPolicy: Always
